name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f78aee03675a6c61e85fb013c83a698cb87083b8c3207f7dc1258e192a9bae3"

[versions]
fabric = "0.17.0"
minecraft = "1.21.1"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
