name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa799a01d09dff1ab79cf2cb7764be30ef4074c77d3bb4b1ccb280a137f42aeb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
