name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe2202a3867e765fd80ea3169727b4789f22f64e223d93883f689c65efee32f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
