name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06606f56d9b5b5247fe0dfd08d9cfa5a53b766aa260d230d839adc05da7da978"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
