name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "852cd9d9e401f0e12414603ca1cc6b6e7638ad3c4781ef4e11e1f722bbfdcafc"

[versions]
fabric = "0.17.0"
minecraft = "1.21.1"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
