name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec40949598f7f6a4907ffbc9efbce5ade99f9449869550001d4c84c22dd4842d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
unsup = "1.2.0-pre1"
