[flavor_groups.shaders]
name = "Shaders"
description = "Allows Shaders to be used to make the game look prettier [Will install Iris, Euphoria Patches, Colorwheel, and Colorwheel Patcher]"
side = "client"
[[flavor_groups.shaders.choices]]
id = "shaderlessbehavior"
name = "No"
[[flavor_groups.shaders.choices]]
id = "shaderedbehavior"
name = "Yes"

[metafile.colorwheel]
flavors = "shaderedbehavior"
[metafile.colorwheel-patcher]
flavors = "shaderedbehavior"
[metafile.euphoria-patches]
flavors = "shaderedbehavior"
[metafile.iris]
flavors = "shaderedbehavior"


[flavor_groups.drpc]
name = "CraftPresence / Discord Rich Presence"
description = "Shows in Discord the pack you're playing and its status"
side = "client"
[[flavor_groups.drpc.choices]]
id = "drpc"
name = "Yes"
[[flavor_groups.drpc.choices]]
id = "drpcno"
name = "No"

[metafile.craftpresence]
flavors = "drpc"
[metafile.unilib]
flavors = "drpc"


[flavor_groups.appleskin]
name = "Apple Skin"
description = "Shows saturation/exhaustion values on the hunger bar, and potential health restored while holding food on the health bar."
side = "client"
[[flavor_groups.appleskin.choices]]
id = "appleskin"
name = "Yes"
[[flavor_groups.appleskin.choices]]
id = "appleskinno"
name = "No"

[metafile.appleskin]
flavors = "appleskin"


[flavor_groups.ui_fix]
name = "UI Fixes"
description = "Fixes some weirdness with Minecraft's UI (Centered Crosshair, Raised)."
side = "client"
[[flavor_groups.ui_fix.choices]]
id = "ui_fixno"
name = "No"
[[flavor_groups.ui_fix.choices]]
id = "centeredcrosshair"
name = "Centered Crosshair"
[[flavor_groups.ui_fix.choices]]
id = "raised"
name = "Raised"
[[flavor_groups.ui_fix.choices]]
id = "ui_fixboth"
name = "Both"

[metafile.centered-crosshair]
flavors = [ "centeredcrosshair", "ui_fixboth" ]
[metafile.raised]
flavors = [ "raised", "ui_fixboth" ]


[flavor_groups.maps]
name = "Map Mods"
description = "What fullscreen map mod would you like to use today?"
side = "client"
[[flavor_groups.maps.choices]]
id = "journeymap"
name = "Journeymap [preferred]"
[[flavor_groups.maps.choices]]
id = "xaeros"
name = "Xaero's"

[metafile.journeymap]
flavors = "journeymap"
[metafile.xaeros-world-map]
flavors = "xaeros"
[metafile.xaeros-minimap]
flavors = "xaeros"


[flavor_groups.animation]
name = "Animation Mods"
description = "Add a little extra liveliness to your gameplay (Falling Leaves, Not Enough Animations)."
side = "client"
[[flavor_groups.animation.choices]]
id = "animation"
name = "Yes"
[[flavor_groups.animation.choices]]
id = "animationno"
name = "No"

[metafile.fallingleaves]
flavors = "animation"
[metafile.not-enough-animations]
flavors = "animation"


[flavor_groups.roll]
name = "Roll Mod"
description = "Camera tweaks for elytra and swimming."
side = "client"
[[flavor_groups.roll.choices]]
id = "rollnone"
name = "None"
[[flavor_groups.roll.choices]]
id = "do-a-barrel-roll"
name = "Do a Barrel Roll"
description = "Changes elytra flight to be more fun and semi-realistic. It achieves this by redesigning movement with a completely unlocked camera orientation in mind, allowing for full pitch, yaw and roll control in flight. [WARNING FOR PEOPLE WHO GET MOTION SICKNESS EASILY]"
[[flavor_groups.roll.choices]]
id = "rolling-down-in-the-deep"
name = "Rolling Down in the Deep / Both"
description = "An addon to Do A Barrel Roll to extend its features to swimming and diving."

[metafile.do-a-barrel-roll]
flavors = ["do-a-barrel-roll", "rolling-down-in-the-deep"]
[metafile.rolling-down-in-the-deep]
flavors = "rolling-down-in-the-deep"


[flavor_groups.ui]
name = "UI Mod"
description = "Extra flavor to your UI."
side = "client"
[[flavor_groups.ui.choices]]
id = "uinone"
name = "None"
[[flavor_groups.ui.choices]]
id = "starhud"
name = "StarHUD"
description = "Display fancy HUDs in your game. If in use with Jade, remember to go into StarHUD's settings, go to Targetted, and set Show HUD to No. Make sure to also readjust Jade's positioning by going to Jade's settings, Mod Settings, Appearance, and then hit Adjust for Overlay Position. Alternatively, you can not use Jade and just use StarHUD's built in Targetter instead."
[[flavor_groups.ui.choices]]
id = "travelers-titles"
name = "Traveler's Titles"
description = "RPG-like titles when entering biomes and dimensions."
[[flavor_groups.ui.choices]]
id = "dynamiccrosshair"
name = "Dynamic Crosshair"
description = "Crosshair that hides or changes depending on your actions"
[[flavor_groups.ui.choices]]
id = "all_ui"
name = "All"

[metafile.starhud]
flavors = ["starhud", "all_ui"]
[metafile.travelers-titles]
flavors = ["travelers-titles", "all_ui"]
[metafile.dynamiccrosshair]
flavors = ["dynamiccrosshair", "all_ui"]


[flavor_groups.sodium_tweaks]
name = "Sodium Tweaks"
description = "Tweaks what Sodium provides and its screen (Sodium Extra, Reese's Sodium Options)."
side = "client"
[[flavor_groups.sodium_tweaks.choices]]
id = "sodium_tweaks"
name = "Yes"
[[flavor_groups.sodium_tweaks.choices]]
id = "sodium_tweaksno"
name = "No"

[metafile.sodium-extra]
flavors = "sodium_tweaks"
[metafile.reeses-sodium-options]
flavors = "sodium_tweaks"


[flavor_groups.dynamiclighting]
name = "LambDynamicLights"
description = "Have dynamic lighting!"
side = "client"
[[flavor_groups.dynamiclighting.choices]]
id = "dynamiclights"
name = "Yes"
[[flavor_groups.dynamiclighting.choices]]
id = "dynamiclightsno"
name = "No"

[metafile.lambdynamiclights]
flavors = "dynamiclights"


[flavor_groups.nvidium]
name = "Nvidium"
description = "Fast Nvidia only rendering engine for Sodium."
side = "client"
[[flavor_groups.nvidium.choices]]
id = "nvidiumno"
name = "No"
[[flavor_groups.nvidium.choices]]
id = "nvidium"
name = "Yes"

[metafile.nvidium]
flavors = "nvidium"


[flavor_groups.jade]
name = "Jade"
description = "Info about what you're looking at in the top middle of your screen. If in use with StarHUD, remember to go into StarHUD's settings, go to Targetted, and set Show HUD to No. Make sure to also readjust Jade's positioning by going to Jade's settings, Mod Settings, Appearance, and then hit Adjust for Overlay Position. Alternatively, you can not use Jade and just use StarHUD's built in Targetter instead."
side = "client"
[[flavor_groups.jade.choices]]
id = "jade"
name = "Yes"
[[flavor_groups.jade.choices]]
id = "jadeno"
name = "No"

[metafile.jade]
flavors = "jade"


[flavor_groups.zoom]
name = "Zoom Mod"
description = "Zoom like you need glasses."
side = "client"
[[flavor_groups.zoom.choices]]
id = "ok-zoomer"
name = "Ok Zoomer"
[[flavor_groups.zoom.choices]]
id = "zoomify"
name = "Zoomify"
description = "If you want more GUI customization than Ok Zoomer."
[[flavor_groups.zoom.choices]]
id = "zoomnone"
name = "None"

[metafile.ok-zoomer]
flavors = "ok-zoomer"
[metafile.zoomify]
flavors = "zoomify"


[flavor_groups.sound]
name = "Sound Mods"
description = "Make your sounds a lot more immersive."
side = "client"
[[flavor_groups.sound.choices]]
id = "soundno"
name = "No"
[[flavor_groups.sound.choices]]
id = "euphonium"
name = "Euphonium"
description = "An immersive sound mod that adds biome, structure, and environment-specific sounds."
[[flavor_groups.sound.choices]]
id = "soundphysicsremastered"
name = "Sound Physics Remastered"
description = "Makes sounds more immersive in a realistic physical manner, with sound attenuation, reverberation, and absorption through blocks"
[[flavor_groups.sound.choices]]
id = "presencefootsteps"
name = "Presence Footsteps"
description = "A sound mod, for your feet."
[[flavor_groups.sound.choices]]
id = "soundphysicsremasteredandpresencefootsteps"
name = "Sound Physics Remastered and Presence Footsteps"
description = "Makes sounds more immersive in a realistic physical manner, with sound attenuation, reverberation, and absorption through blocks, now also with your feet too!"
[[flavor_groups.sound.choices]]
id = "sound-all"
name = "All"
description = "Sound physics, foot sound physics, and environmental sound overhaul?! Are you trying to be overwhelmed?"

[metafile.sound-physics-remastered]
flavors = [ "soundphysicsremastered", "soundphysicsremasteredandpresencefootsteps", "sound-all" ]
[metafile.presence-footsteps]
flavors = [ "presencefootsteps", "soundphysicsremasteredandpresencefootsteps", "sound-all" ]
[metafile.pv-addon-soundphysics]
flavors = [ "soundphysicsremastered", "soundphysicsremasteredandpresencefootsteps", "sound-all" ]
[metafile.euphonium]
flavors = [ "euphonium", "sound-all" ]


[flavor_groups.controller]
name = "Controller Mod"
description = "Have the option to play with a controller."
side = "client"
[[flavor_groups.controller.choices]]
id = "controllernone"
name = "None"
[[flavor_groups.controller.choices]]
id = "controlify"
name = "Controlify"
[[flavor_groups.controller.choices]]
id = "midnightcontrols"
name = "MidnightControls"
description = "Controlify is preferred. Only use if it doesn't work for you."

[metafile.controlify]
flavors = "controlify"
[metafile.midnightcontrols]
flavors = "midnightcontrols"

[flavor_groups.flashback]
name = "Flashback"
description = "A better ReplayMod"
side = "client"
[[flavor_groups.flashback.choices]]
id = "flashback"
name = "Yes"
[[flavor_groups.flashback.choices]]
id = "flashnt"
name = "No"

[metafile.flashback]
flavors = "flashback"